
DROP FUNCTION IF EXISTS Kazu(param1 INT, param2 INT, param3 INT);

CREATE OR REPLACE FUNCTION Kazu(param1 INT, param2 INT DEFAULT -1, param3 INT DEFAULT -1) RETURNS INT AS $$
BEGIN

   IF param2 < 0 THEN RETURN 1;
   ELSIF param3 < 0 THEN RETURN 2;
   ELSE RETURN 3;
   END IF;
END
$$ LANGUAGE plpgsql VOLATILE STRICT;



